### ISSUE TITLE
User Story: Search actors and directors by name.

### ISSUE THREAD

**Issue by cla-cif** [cla-cif/movie-DB-2000s#3]
As a **film blogger** I want my **search to be effective** so that **I can search actors and directors by full name or partial name and, match foreign alphabet characters I don't have on my keyboard by typing the closest character I can think of.**

## Acceptance criteria:
- I want to be able to write in lower or upper case.
- I want to be able to find names by typing just one letter. 
- I want to match similar names that differ only by diacritical marks.

## Tasks
- [x] apply lowercase method to user's input and dataframe.
- [x] implement nested loops to match partial strings. 
- [x] apply normalization method to return the Unicode normal form for the user's input and dataframe.

**Comment by cla-cif** [comment]
The three acceptance criteria were successfully met. Strings containing `'` (apostrophe) which may act as a word boundary, were also successfully handled and don't pose a problem in the query.
