### ISSUE TITLE
User Story: Clear and direct instructions

### ISSUE THREAD

**Issue by cla-cif** [cla-cif/movie-DB-2000s#4]
As a **film blogger** I want to **interact with the app and get to the desired result in the most direct and clear way possible** so that **I get the information I want without breaking my workflow and without "getting lost" in the app because of unclear instructions**.

## Acceptance criteria:
- Clear, easy and unmistakable instructions.
- Avoid "dead ends" which would interrupt the workflow. 
- Help sections always available.

## Tasks
- [x] Write brief and clear instructions avoiding technical terms.
- [x] Maximise the visual clarity by consistently assigning a different color to instructions, error messages, output and highlights.
- [x] Structure the app so that the CLI is always ready to receive next input (avoid dead ends). 
- [x] Implement input validation. 
- [x] Crete "help" section and make it always reachable. 
- [x] Allow the user to quit the program at any point while using the app.

**Comment by cla-cif** [comment]
All the tasks completed and well documented in the [README.md](https://github.com/cla-cif/movie-DB-2000s#readme) file.
